#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mcelog
Version  : 129
Release  : 1
URL      : https://github.com/andikleen/mcelog/archive/v129.tar.gz
Source0  : https://github.com/andikleen/mcelog/archive/v129.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: mcelog-bin
Requires: mcelog-doc

%description
mcelog is the user space backend for logging machine check errors
reported by the hardware to the kernel. The kernel does the immediate
actions (like killing processes etc.) and mcelog decodes the errors
and manages various other advanced error responses like
offlining memory, CPUs or triggering events. In addition
mcelog also handles corrected errors, by logging and accounting them.

%package bin
Summary: bin components for the mcelog package.
Group: Binaries

%description bin
bin components for the mcelog package.


%package doc
Summary: doc components for the mcelog package.
Group: Documentation

%description doc
doc components for the mcelog package.


%prep
%setup -q -n mcelog-129

%build
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mcelog

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man5/*
%doc /usr/share/man/man8/*
